name: 'Hello World'
description: 'Prints hello world to the screen'
inputs:
  person_name:
    description: 'The person to greet hello'
    required: true
    default: 'Gopi'
runs:
  using: composite
  steps:
    - run: echo Hello ${{inputs.person_name}} from ${GITHUB_REF##*/}.
      shell: bash
    - run: sudo apt-get install libboost-all-dev
      shell: bash
    - run: b2 --version