name: 'Push to Remote Branch'
description: 'Pushes a directory created in this branch to another branch'
inputs:
  github_token:
    description: 'Github Token'
    required: true

runs:
  using: composite
  steps:
    - run: chmod +x ./.github/actions/create-example-dir/push-script.sh
      shell: bash
    - run: ./.github/actions/create-example-dir/push-script.sh ${{inputs.github_token}}
      shell: bash