name: learn-github-actions
on : [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - env:
          super_secret: ${{secrets.GH_Token}}
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world-action
        with:
          person_name: 'Gopi Krishna Menon'
      - uses: ./.github/actions/create-example-dir